################################################################################
# Copyright 2018 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 2.0.1
# Author: "Ben Rose" <benjaminshannonrose@gmail.com>

# interactions_steps.rb is used to interact with elements on the page.

When /^the user enters (?:[^\"]*) on the ([^\"]*):$/ do |component, table|
  arr = table.raw
  arr.each do |i|
    action = i[0]
    data = i[1]
    $object_helper.get_object(component).send(action,data)
  end
end


When /^the user enters \"([^\"]*)\" into the ([^\"]*) (?:in|on|of) the ([^\"]*)$/ do |data, action, object|
  $object_helper.get_object(object).send(action, data)
end

When /^the user clicks ([^\"]*) (?:titled|called|labeled|named) \"([^\"]*)\" on the ([^\"]*)$/ do |action, data, object|
  $object_helper.get_object(object).send(action, data)
end

And /^the user clicks ([^\"]*) (?:in|on) the ([^\"]*)$/ do |action, object|
  $object_helper.get_object(object).send(action)
end