################################################################################
# Copyright 2018 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 2.0.1
# Author: "Ben Rose" <benjaminshannonrose@gmail.com>

# precondition_steps.rb is used to define steps that contain multiple steps to come to a certain start of a scenrario.
# For example: "Given the user is logged in" will contain all steps done before logging in

Given(/^the user navigates to the "(.*?)" page$/) do |page|
  # Get the value of the configuration (see /config/config.yml)

  # First grab the root URL defined in the config
  url = env('pages.root')
  # Then add the page specific part to the URL
  url += env("pages.#{page}")

  # Go to the URL
  browser.goto url
end


