################################################################################
# Copyright 2018 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 2.0.1
# Author: "Ben Rose" <benjaminshannonrose@gmail.com>

# validation_steps.rb is used to confirm that certain elements are displayed on the page.

Then /^the user should see ([^\"]*) (?:of|in|on) the ([^\"]*)$/ do |action, object|
  $object_helper.get_object(object).send(action)
end

And /^the ([^\"]*) (?:of|on) the ([^\"]*) should read \"([^\"]*)\"$/ do |action, object, data|
  $object_helper.get_object(object).send(action, data)
end

Then /^the post titled \"([^\"]*)\" should ([^\"]*) (?:from|of|on) the ([^\"]*)$/ do |data, action, object|
  $object_helper.get_object(object).send(action, data)
end

Then(/^the user (?:should|shouldn't) see ([^"]*) that reads "([^"]*)" on the ([^"]*)$/) do |action, data, object|
  $object_helper.get_object(object).send(action, data)
end
